### ISSUE TITLE
AMXX] Run time error 10 (plugin "proxy_check.amxx") (native "grip_json_object_get_value") - debug not enabled!

### ISSUE THREAD

**Issue by ady2324** [etojuice/proxy_check#1]
hi all
i have this error in my server

AMXX] Run time error 10 (plugin "proxy_check.amxx") (native "grip_json_object_get_value") - debug not enabled!

i use amxmodx 1.8.3

**Comment by etojuice** [comment]
Please add "debug" next to plugin name in plugins list (plugins.ini)

**Comment by etojuice** [comment]
@ady2324, I've put version 2.1 on "dev" branch. Try it and tell me if the problem still persists.

https://github.com/etojuice/proxy_check/blob/dev/scripting/proxy_check.sma

**Comment by ady2324** [comment]
sorry for delay

the error gives when max limit reach to website

i will try the new version
